### ISSUE TITLE
 Audio only whiteboard

### ISSUE THREAD

**Issue by RamanHacks** [plutoless/eEducation#186]
How do I initialize the classroom with just the audio feature enabled for real time communication (i.e. to disable the video feature from backend for all)?

**Comment by leavesster** [comment]
Sorry  for late reply. We have only recently started building this project. 
As RTC is not a basic service we provide, we have only wrapped it up as a third party and cannot provide a more specific response at this time. You can wait for a response to the issue AgoraIO-Usecase/eEducation#5 you raised with the corresponding rtc vendor.

**Comment by srs888001** [comment]
You can refer https://docs.agora.io/en/Video/API%20Reference/java/index.html to turn off all video related functions.
For example: disablevideo,setdefaultmuteallremotevideostreams,mutevideo.
